- hosts: servers
  become: yes
  vars:
    crc_version: latest
    use_all_in_one_haproxy: true
    haproxy_ip: ""
    use_all_in_one_dnsmasq: true 
    log_level: info
    ocp4_release: latest
    remove_oc_tool: false
    delete_crc_deployment: false
    forward_server: 1.1.1.1
  roles:
  - ansible-codeready