- name: Copying over pull-secert.txt
  template:
    src: templates/pull-secret.txt.j2
    dest:  "{{ pull_secert_path }}"
    owner: admin
    group: admin
    mode: 0666
  tags:
  - start_crc_deployment

- name: ensure libvirtd service
  systemd:
    name: libvirtd
    state: started
    enabled: yes
  register: libvirtd_status
  become: true
  become_user: root
  tags:
  - start_crc_deployment

- debug: var=libvirtd_status.state
  tags:
  - start_crc_deployment

- name: Libvirtd service failed to start
  fail:
    msg: " Libvirtd service failed to start {{ libvirtd_status.state }}"
  when: "'started' not in libvirtd_status.state"
  tags:
  - start_crc_deployment

- name: Start CodeReady Deployment
  shell: |
    set -o pipefail
    crc start -c {{ cpu }} -m {{ memory }} -p {{ pull_secert_path }} --log-level {{ log_level }} | tee /tmp/install_status.log
  tags:
  - start_crc_deployment
