---
# defaults file for codeready-containers-hack
crc_version: latest
crc_url: https://mirror.openshift.com/pub/openshift-v4/clients/crc/
crc_file_name: crc-linux-amd64.tar.xz
pull_secret_path: ~/Downloads/pull-secret
use_all_in_one_haproxy: true
haproxy_ip: ""
use_all_in_one_dnsmasq: true 
log_level: info
crc_ip_address: 192.168.130.11
delete_crc_deployment: false
forward_server: 1.1.1.1

ocp4_release: latest
ocp4_release_url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp4_release }}/"
ocp4_client: "openshift-client-linux.tar.gz"
remove_oc_tool: false

# 6 vCPU
cpu: 6
# 12G of RAM
memory: 12288