- name: "Remove /tmp/{{ crc_file_name }} if exists"
  file:
    path:  "/tmp/{{ crc_file_name }}"
    state: absent
  ignore_errors: true 

- name: Get crc sha from openshift site
  get_url: 
    url: "https://mirror.openshift.com/pub/openshift-v4/clients/crc/{{ ocp4_release }}/sha256sum.txt"
    dest: /tmp/sha256sum.txt

- name: set crc_sha
  shell: cat /tmp/sha256sum.txt | grep crc-linux-amd64.tar.xz | awk '{print $1}'
  register: crc_sha

- name: Download Code Ready Containers
  get_url:
    url: "{{ crc_url }}/{{ crc_version }}/{{ crc_file_name }}"
    dest: "/tmp/{{ crc_file_name }}"
    checksum: "sha256:{{ crc_sha.stdout }}"
  tags:
  - download_crc

- name: Extract crc-linux-amd64.tar.xz into /tmp/
  script: "files/extract_crc_file.sh"
  become: true
  become_user: root
  tags:
  - extract_crc

- name: Check to see is crc installed
  command: crc -h
  changed_when: false
  failed_when: false
  register: crc_installed
  tags:
  - extract_crc

- name: Check CodeReady Containers executable status
  fail:
    msg: "CRC appears to be missing, install failed"
  when: crc_installed.rc == 2
  tags:
  - extract_crc